services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassw0rd!123"
      SA_PASSWORD: "StrongPassw0rd!123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: ./Backend
    container_name: backend
    depends_on:
      - sqlserver
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dapp.jwt.secret=TestSecretKeyTestSecretKeyTestSecretKey123456
        -Dapp.jwt.access-expiration=3600000
        -Dapp.jwt.refresh-expiration=604800000
        -Dspring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=appdb;encrypt=false;trustServerCertificate=true
        -Dspring.datasource.username=sa
        -Dspring.datasource.password=StrongPassw0rd!123

  frontend:
    build: ./Frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  sqlserver_data: