services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassw0rd!123"
      SA_PASSWORD: "StrongPassw0rd!123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: ./Backend
    container_name: backend
    depends_on:
      - sqlserver
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      APP_JWT_SECRET: "TestSecretKeyTestSecretKeyTestSecretKey123456"
      APP_JWT_ACCESS_EXPIRATION: "3600000"
      APP_JWT_REFRESH_EXPIRATION: "604800000"
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=appdb;encrypt=false;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "StrongPassw0rd!123"

  frontend:
    build: ./Frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  sqlserver_data: